# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiDataLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('timestamp', models.BigIntegerField()),
                ('field1_data', models.FloatField()),
                ('field2_data', models.FloatField()),
                ('field3_data', models.FloatField()),
                ('field4_data', models.FloatField()),
                ('field5_data', models.FloatField()),
                ('field1_name', models.CharField(default='label1', max_length=64)),
                ('field2_name', models.CharField(default='label2', max_length=64)),
                ('field3_name', models.CharField(default='label3', max_length=64)),
                ('field4_name', models.CharField(default='label4', max_length=64)),
                ('field5_name', models.CharField(default='label5', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('timestamp', models.BigIntegerField()),
                ('field1_data', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('timestamp', models.BigIntegerField()),
                ('field1_data', models.FloatField()),
                ('field1_name', models.CharField(default='temperature', max_length=64)),
            ],
        ),
    ]
