# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 07:46
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User

from ..utils import initial_fake_data

def generate_fake_data(apps, schema_editor):
    TemperatureLog = apps.get_model("logs", "TemperatureLog")
    StatusLog = apps.get_model("logs", "StatusLog")
    MultiDataLog = apps.get_model("logs", "MultiDataLog")

    for user in User.objects.all():
        initial_fake_data(user)

class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        #migrations.RunPython(generate_fake_data),
    ]
