# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20160325_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='multidatalog',
            name='data_source',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='statuslog',
            name='data_source',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='temperaturelog',
            name='data_source',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
